import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Discover, Sidebar, TopNav } from '@/components'
import { Box, Hide, HStack } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <Box>
            <TopNav  />
            <HStack>
            <Hide below='md' >
        <Box h="90vh"  w={{md : "30%" , lg : "300px"}} borderTop={2} borderColor="yellow"   >
        <Sidebar />
        </Box>
        </Hide>
      <Discover  />
            </HStack>
          </Box>
      
      </main>
    </>
  )
}
